opensquare-network/paid-qa

packages/site/src/components/Chain/ChainSelector.js, packages/site/src/components/Header.js
=> component: Chain select dropdown

packages/site/package.json, packages/site/src/components/Header.js, packages/ui/lib/Account/AccountItem.js, packages/ui/lib/Account/AccountSelector.js, packages/ui/lib/Account/Address.js, packages/ui/lib/Account/Avatar.js, yarn.lock
=> component: Account select dropdown

packages/site/package.json, packages/site/public/imgs/icons/close.svg, packages/site/src/components/Connect.js, packages/site/src/components/ConnectWallet.js, packages/site/src/components/Header.js, packages/site/src/store/reducers/accountSlice.js, packages/site/src/store/reducers/index.js, packages/ui/lib/Account/ConnectedAccount.js, packages/ui/lib/Chain/ChainSelector.js, packages/ui/lib/utils/constants.js, packages/ui/lib/utils/cookie.js, packages/ui/lib/utils/hooks.js, yarn.lock
=> implement user connect with wallet #21

packages/site/src/components/MobileMenu.js
=> improve <Header> responsive, #59

packages/site/src/components/Create/index.js
refs https://test.opensquare.io/space/rmrk/create
=> new topic reponsive css

packages/site/src/components/Topic.js, packages/site/src/components/TopicsList.js
=> style: fix topic list(skeleton) layout

packages/site/src/components/TopicsList.js, packages/site/src/pages/Home.js
=> fix topic list skeleton loading state bug

packages/site/src/components/Post/Promises/index.js
=> fix support button size under mobile view , #137

packages/ui/lib/imgs/icons/caret-right.svg, packages/ui/lib/styled/Pagination.js
=> fix pagination style, #133

packages/ui/lib/styled/Pagination.js
=> style fixup: pagination #80

packages/site/src/components/Funders.js
=> Fix funders style

packages/site/src/components/AssetSelector/index.js
=> fix current option hidden in selector, #141

packages/site/src/components/Post/Answers/Item.js, packages/site/src/components/Post/Answers/index.js
=> Refs #189, show replies height

packages/ui/lib/Account/AccountSelector.js
=> fix account selector style, #185

packages/site/src/components/Notification/NotificationList.js, packages/site/src/components/Notification/ReplyItem.js
=> implementNotificationItem #216

packages/site/src/components/Notification/DiscussionItem.js, packages/site/src/components/Profile/AnswerList.js, packages/site/src/pages/Notifications.js, packages/site/src/pages/Profile.js, packages/ui/lib/Preview/MicromarkMd.js
=> improve: use a minimal mode for RichText in some pages

packages/site/src/components/Profile/AnswerList.js, packages/site/src/components/Profile/Header.js, packages/site/src/components/Profile/TopicsList.js, packages/site/src/components/Profile/User.js
=> profile header ui refactor, #287

packages/site/src/utils/hooks.js
=> fix component memory leak, #292

packages/site/src/components/Tabs.js
=> style fix: profile page responsive

packages/site/src/components/Profile/PromisesList.js, packages/site/src/components/Tag.js
=> fix: show multi symbol support in profile promises

packages/site/src/components/Profile/AnswersList.js, packages/site/src/components/Profile/FundsList.js, packages/site/src/components/Profile/PromisesList.js, packages/site/src/components/Profile/RewardsList.js, packages/site/src/components/Profile/TopicsList.js, packages/site/src/components/Profile/styled/ListWrapper.js
=> fix responsive, #319

packages/site/src/components/Explorer.js
=> bugfix: explorer no more override, #324

packages/site/src/components/Post/Detail/index.js, packages/site/src/components/Profile/AnswersList.js, packages/site/src/components/Profile/FundsList.js, packages/site/src/components/Profile/PromisesList.js, packages/site/src/components/Profile/RewardsList.js, packages/site/src/components/Profile/TopicsList.js, packages/site/src/components/TopicsList.js, packages/site/src/pages/Notifications.js, packages/ui/lib/Skeleton/DetailLoader.js, packages/ui/lib/Skeleton/ListLoader.js
=> feat(ui): skeleton

packages/site/src/components/NoPost.js, packages/site/src/components/NoReplies.js, packages/site/src/components/TopicsList.js, packages/ui/lib/NoData/index.js, packages/ui/src/stories/NoData.stories.js
=> feat(ui): nodata

packages/site/src/components/NoPost.js
=> chore(site): comment

packages/ui/src/stories/Tabs.stories.js, packages/ui/src/stories/Tag.stories.js
storybook prefer `primary` for basic
=> refactor(story): prefer primary

packages/ui/.storybook/main.js, packages/ui/.storybook/preview-head.html
=> feat(storybook): use css

packages/ui/src/stories/Container.stories.js, packages/ui/src/stories/Layout.stories.js
=> feat(story): layout and container

packages/ui/.storybook/main.js, packages/ui/package.json, yarn.lock
close #386 
create react app now is webpack 5
=> feat(storybook): webpack 5 with svg

packages/site/src/components/Post/Detail/Resolve.js, packages/site/src/components/Post/Promises/Item.js, packages/site/src/components/ResolveModal.js
=> fix: display multiple token support in resolve modal, #417

packages/site/src/components/ConnectModal.js, packages/site/src/components/FundModal.js, packages/site/src/components/ReportModal.js, packages/site/src/components/ResolveModal.js, packages/site/src/components/SupportModal.js, packages/ui/lib/Modal/index.js, packages/ui/lib/imgs/icons/close.svg, packages/ui/src/stories/Modal.stories.js
close #405 close #410
designed apis see #405 
from
apply to site
add story
=> feat(ui): modal

packages/ui/.babelrc, packages/ui/.gitignore, packages/ui/package.json
close #425 
```js
import Button from '@osn/common-ui/es/styled/Button'
```
To use micromarkmd in nextjs, should disable the ssr, micromark uses window api
=> feat(ui): build esm

packages/server/src/features/account/account.controller.js, packages/server/src/models/resolve.js, packages/server/src/services/resolve.service.js, packages/site/src/components/Profile/PromisesList.js
=> fix: promise status display in profile page, #397

packages/ui/lib/Preview/index.js, packages/ui/lib/RichEdit/index.js
close #437 
`props.minHeight: number`
- move min-height to rich editor
=> feat(ui): preview props.minHeight

packages/ui/lib/Tag/index.js, packages/ui/src/stories/Tag.stories.js
=> feat(ui): tag

packages/site/craco.config.js, packages/site/src/components/TagList.js, packages/ui/lib/index.js
=> refactor(site): apply Tag

packages/ui/lib/RichEdit/index.js
#441 
in some places, we only need to show the Preview button and modify css.
in other projects
=> feat(ui): rich editor add classnames

packages/ui/lib/Modal/index.js, packages/ui/src/stories/Modal.stories.js
=> fix(ui): modal footer

packages/ui/lib/Tag/index.js, packages/ui/src/stories/Tag.stories.js
BREAKING CHANGE: remove props.status
close #449 
note: preset colors key name is from design draft.
=> feat!(ui): tag

packages/site/src/services/chainApi.js
=> polish: Handle extrinsic failure. #433

packages/site/src/components/Post/Detail/Appendants.js, packages/site/src/components/Post/Detail/index.js
=> fix: prevent append to resolved topics, #474

packages/site/src/components/Header.js, packages/ui/lib/Header/index.js, packages/ui/src/stories/Header.stories.js
=> fix(ui): header universal

packages/site/package.json, packages/ui/package.json, yarn.lock
=> bugfix: use styled-component 5.3.1 to fix extend bug

packages/ui/lib/RichEdit/index.js, packages/ui/package.json, packages/ui/src/stories/RichEditor.stories.js
=> feat(ui): rich editor control button display props

packages/site/src/components/Create/index.js
=> refactor(site): rich editor button props

packages/ui/lib/Breadcrumb/Breadcrumb.js, packages/ui/lib/Breadcrumb/BreadcrumbItem.js, packages/ui/lib/Breadcrumb/index.d.ts, packages/ui/lib/Breadcrumb/index.js, packages/ui/lib/Breadcrumb/types.ts, packages/ui/lib/index.d.ts, packages/ui/lib/index.js, packages/ui/lib/styles/colors.js, packages/ui/package.json, packages/ui/src/stories/Breadcrumb.stories.js
close #485 
breadcrumb
breadcrumb item
=> feat(ui): breadcrumb v0.0.52

packages/site/src/components/TopicsList.js
=> fix(site): eliminate page-1

packages/site/src/App.js, packages/site/src/components/ScrollToTop.js
=> reset scroll when page switched, #520

packages/site/src/components/Notification/NotificationItem.js, packages/site/src/pages/Notifications.js
- missing mention
- semantic
- reset scroll
=> fix(site): notification item

packages/ui/lib/Card/Card.js, packages/ui/src/stories/Card.stories.js
=> docs(story): card

packages/ui/lib/NoData/index.js
=> refactor(ui): no data

packages/ui/lib/Card/Card.js, packages/ui/src/stories/Card.stories.js
=> feat(ui): card prefix suffix

packages/ui/lib/List/List.js
=> feat(ui): list no data support

packages/ui/lib/Card/Card.js, packages/ui/lib/List/List.js
#539 
card: prefix and suffix
list: reset margin
=> fix(ui): card & list

packages/site/src/components/Notification/NotificationItem.js
reply content allow `a` element
close #538
=> fix(site): page notification item

packages/ui/lib/imgs/icons/caret-down.svg, packages/ui/lib/styled/Dropdown.js, packages/ui/lib/styles/colors.js, packages/ui/src/stories/DropdownSelector.stories.js
~~https://github.com/react-component/virtual-list/blob/master/src/ScrollBar.tsx~~
=> feat(ui): dropdown improvement

packages/site/src/components/Post/Promises/Item.js, packages/site/src/components/ResolveModal.js
=> feat(site): resolve modal improvement

packages/ui/lib/Tag/index.js, packages/ui/lib/styles/colors.js, packages/ui/package.json
=> fix(ui): v0.0.56 tag use background

packages/site/src/components/TagList.js
=> feat(site): colorful amount tag

packages/site/src/components/Post/Detail/Appendants.js
=> feat(site): page post appendants icon

packages/site/src/components/Post/Detail/Resolve.js, packages/site/src/components/Post/Detail/index.js
=> fix(site): post detail divider

packages/ui/.babelrc, packages/ui/lib/Time/utils.test.js, packages/ui/package.json, yarn.lock
=> test(ui): setup jest

packages/ui/lib/List/List.js, packages/ui/lib/List/ListItem.js, packages/ui/lib/List/index.d.ts, packages/ui/lib/List/types.ts, packages/ui/src/stories/List.stories.js
=> feat(ui): list loading

packages/common/package.json, packages/ui/package.json
=> bump package version

packages/common/package.json, packages/site/src/components/ConnectModal.js, packages/ui/package.json
revert common deps #613 to close https://github.com/opensquare-network/collaboration/issues/781
=> fix: package deps & bump (common 0.0.11, ui 0.0.66)

packages/ui/lib/Chain/ChainIcon.js, packages/ui/package.json
=> fix(ui): chain icon compat nextjs (ui 0.0.68)

packages/site/src/pages/Notifications.js
=> fix(site): page notification duplicated no data

packages/site/src/components/Notification/NotificationItem.js
=> fix: page notifications wrong participant

packages/site/src/components/Notification/NotificationItem.js
=> fix: byWho fallback

packages/site/src/components/Post/Answers/index.js
=> feat: render mention item as network user

packages/site/package.json, packages/site/src/components/Account/AccountItem.js, packages/site/src/components/Explorer.js, packages/site/src/components/Header.js, packages/site/src/components/Notification/NotificationItem.js, packages/site/src/components/Notification/NotificationTabs.js, packages/site/src/components/Post/Answers/index.js, packages/site/src/components/Post/index.js, packages/site/src/components/Profile/Header.js, packages/site/src/components/Profile/ProfilePromiseItem.js, packages/site/src/components/Profile/User.js, packages/site/src/components/Profile/styled/ListWrapper.js, packages/site/src/components/User/IdentityOrAddr.js, packages/site/src/pages/Home.js, packages/site/src/store/reducers/accountSlice.js, packages/site/src/utils/constants.js, yarn.lock
=> fix: migrate osn constants

packages/ui/lib/Identity/IdentityUser.js, packages/ui/lib/Identity/MentionIdentityUser.js, packages/ui/lib/styles/colors.js
=> feat(ui): identity user

packages/site/package.json, packages/site/src/components/Notification/NotificationItem.js, packages/site/src/components/Post/Answers/Item.js, packages/site/src/components/Profile/ProfileAnswerItem.js, packages/site/src/components/Profile/ProfileDataList.js, packages/ui/lib/index.js, yarn.lock
=> feat: mention identity user

packages/common/src/services/identity.js
=> fix(common): identity server host

packages/site/src/components/Dash.js, packages/site/src/components/Notification/NotificationItem.js, packages/site/src/components/Profile/ProfileAnswerItem.js, packages/site/src/components/Profile/ProfileFundItem.js, packages/site/src/components/Profile/ProfileRewardItem.js
=> fix(site): dash

packages/ui/lib/Identity/LinkIdentityUser.js, packages/ui/lib/Identity/MentionIdentityUser.js
=> feat(ui): link identity prop target

packages/ui/lib/RichEdit/index.js
=> fix(ui): rich editor pass identifier

packages/site/package.json, packages/site/src/components/Post/Answers/index.js, yarn.lock
=> fix(site): editor preview mentioned user link

packages/site/src/components/Notification/NotificationItem.js
=> Fix: notification item style

packages/ui/lib/Icon/LoadingDot/index.js, packages/ui/lib/Icon/LoadingDot/styled.js, packages/ui/lib/Icon/index.d.ts, packages/ui/lib/Icon/index.js, packages/ui/lib/index.d.ts, packages/ui/lib/index.js, packages/ui/src/stories/Icon.stories.js
- loading dot
- expose icons
-
=> feat: icon
